### ISSUE TITLE
구성 중 이슈

### ISSUE THREAD

**Issue by NownS** [BORI-BoB/L7-monitor#16]
1. requirments.txt 에 cryptography 패키지 추가 필요 - 추가바람!
2. docker run 수행 시 로컬에서 테스트하기 위해서는 docker run -dp 3306:3306과 같이 호스트:도커 포트 연동 필요(차후 docker-compose를 이용하여 구성하는 경우는 도커 내 동일 네트워크에서 사용할 예정이라 상관없을듯)
3. bWAPP access.log로 연동시켜 본 결과, 파싱에 문제 발생, 정규표현식 변경 필요할 듯(요건 내가 더 고민해볼게요)
4. 현재 DB 연결까지는 성공, 파이썬 데몬을 이용하여 데이터 넣는 과정에서 오류 발생(3번 이유)

(요거 아직 PR 확인 못하고 기존 파일로 확인한 내용인데, 3번은 다시 확인해 봐야할듯)

**Comment by NownS** [comment]
3번 디비 설계 이슈로 확인, 해결완료

**Comment by lauvsong** [comment]
1번 추가 + PR 완료
